# Netlify configuration for SecondBrain Frontend

[build]
  # Base directory for the build
  base = "frontend"
  
  # Build command
  command = "npm run build"
  
  # Publish directory (relative to base)
  publish = "dist"

[build.environment]
  # Backend API URL (Render)
  VITE_API_HOST = "https://second-brain-mfob.onrender.com"

# Redirect all requests to index.html for React Router to handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
