# Netlify configuration for SecondBrain Frontend

[build]
  # Base directory for the build
  base = "frontend"
  
  # Build command
  command = "npm run build"
  
  # Publish directory (relative to base)
  publish = "dist"

# Redirect all requests to index.html for React Router to handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables (set these in Netlify dashboard as well)
# VITE_API_HOST = your backend URL from Render
